# Generated by Django 5.2.10 on 2026-03-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0020_cropbatch_distributor_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCropPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_preferences', to='supplychain.stakeholderprofile')),
            ],
            options={
                'ordering': ['crop_name'],
                'unique_together': {('farmer', 'crop_name')},
            },
        ),
    ]
