# Generated by Django 5.2.10 on 2026-03-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0022_batchevent_blockchain_block_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbatch',
            name='integrity_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('INTEGRITY_FAILED', 'Integrity Failed')], default='UNVERIFIED', max_length=32),
        ),
        migrations.CreateModel(
            name='BatchIntegrityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Batch Created'), ('TRANSPORT_REQUESTED', 'Transport Requested'), ('TRANSPORT_ACCEPTED', 'Transport Accepted'), ('TRANSPORT_STARTED', 'Transport Started'), ('ARRIVED_AT_DISTRIBUTOR', 'Arrived at Distributor'), ('ARRIVAL_CONFIRMED_BY_DISTRIBUTOR', 'Arrival Confirmed by Distributor'), ('DELIVERED_TO_DISTRIBUTOR', 'Delivered to Distributor'), ('STORED', 'Stored by Distributor'), ('INSPECTED', 'Inspected'), ('INSPECTION_PASSED', 'Inspection Passed'), ('INSPECTION_FAILED', 'Inspection Failed'), ('TRANSPORT_REQUESTED_TO_RETAILER', 'Transport Requested to Retailer'), ('IN_TRANSIT_TO_RETAILER', 'In Transit to Retailer'), ('ARRIVED_AT_RETAILER', 'Arrived at Retailer'), ('ARRIVAL_CONFIRMED_BY_RETAILER', 'Arrival Confirmed by Retailer'), ('DELIVERED_TO_RETAILER', 'Delivered to Retailer'), ('LISTED', 'Listed for Retail'), ('SOLD', 'Sold to Consumer'), ('TRANSPORT_REJECTED', 'Transport Rejected'), ('SUSPENDED', 'Batch Suspended'), ('FULLY_SPLIT', 'Batch Fully Split')], max_length=32)),
                ('blockchain_hash', models.CharField(max_length=64)),
                ('recomputed_hash', models.CharField(max_length=64)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_logs', to='supplychain.cropbatch')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
