# Generated by Django 5.2.11 on 2026-03-13 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0023_cropbatch_integrity_status_batchintegritylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('modified_by_role', models.CharField(choices=[('farmer', 'Farmer'), ('transporter', 'Transporter'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('consumer', 'Consumer'), ('admin', 'Admin')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='supplychain.cropbatch')),
                ('modified_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_edits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['batch', '-timestamp'], name='supplychain_batch_i_8aea80_idx'), models.Index(fields=['field_name'], name='supplychain_field_n_b5c557_idx')],
            },
        ),
    ]
