# Generated by Django 5.2.10 on 2026-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0021_farmercroppreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchevent',
            name='blockchain_block_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchevent',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='batchevent',
            name='snapshot_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='is_blockchain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='last_anchored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
